name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build

      - name: Generate Minimal Changelog
        run: |
          npm install -D conventional-changelog conventional-changelog-conventionalcommits conventional-changelog-angular
          npx conventional-changelog -p angular -i CHANGELOG.md -s \
            --commit-path "" \
            --types "feat,fix,BREAKING CHANGE"
          echo "Generated Changelog:"
          cat CHANGELOG.md
          
      - name: Publish to npm
        run: |
          git config --global user.email "sashakosyak@yahoo.com"
          git config --global user.name "kossyak"
          
          git checkout -b release/v${{ github.event.inputs.version }}
          npm version "${{ github.event.inputs.version }}" --no-git-tag-version
          
          git add package.json package-lock.json CHANGELOG.md
          git commit -m "chore: release v${{ github.event.inputs.version }}"
          git push origin release/v${{ github.event.inputs.version }}
          
          git tag "v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"
          
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_LESTA }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Release v${{ github.event.inputs.version }}"
          body: "Automatic release PR"
          branch: "release/v${{ github.event.inputs.version }}"
          base: main    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
